-----BEGIN CERTIFICATE-----
MIIFEzCCA/ugAwIBAgIQU/YxlFrZ64wYlMYUX5G1RzANBgkqhkiG9w0BAQsFADCB
wjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlTdW5ueXZhbGUx
FTATBgNVBAoTDE9wc3dhcmUgSW5jLjEVMBMGA1UECxMMT3Bzd2FyZSBUZWFtMSIw
IAYJKoZIhvcNAQkBFhNzdXBwb3J0QG9wc3dhcmUuY29tMRUwEwYDVQQDEwxib290
c3RyYXAtY2ExKTAnBgNVBAUTIDUzZjYzMTk0NWFkOWViOGMxODk0YzYxNDVmOTFi
NTQ2MB4XDTI1MDEwODEzMzY0NVoXDTM1MDEwNzEzMzY0NVowgZQxCzAJBgNVBAYT
AlVTMQswCQYDVQQIEwJDQTESMBAGA1UEBxMJU3Vubnl2YWxlMRUwEwYDVQQKEwxP
cHN3YXJlIEluYy4xFTATBgNVBAsTDE9wc3dhcmUgVGVhbTESMBAGA1UEAxMJYm9v
dHN0cmFwMSIwIAYJKoZIhvcNAQkBFhNzdXBwb3J0QG9wc3dhcmUuY29tMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoeSdOsnam+J2tyTFW81Y3f8FjNoX
oXzvazPKk9FG5dVWi58zVoITCmRJLONeYE82D/+Y1+YJGcXdLj0eRnFgXBBHwZ8k
Z8nnIc6T0Ik4mkQoxrAvPfvlHc9Po60kxB7wAzqE7sBwMbaPiZfcadBtGwKreNgT
+e/VE2k/GCe61Xaz8ZjnfSMuYKUl1oC6/h7UmBEl0UWxKMefUoAD3Y4mnX8j4ppf
TZSzbF4Tp9cs+OI8w5OjLLGPL3TzB720dK/1MzFIoutKPYMKsKQcdPsLMBgGiPi4
6wC8cqe65FtMoT/Z5CoG2haRf2xuzvdo78gzSHleoVd7bonOT+1vh1SZXwIDAQAB
o4IBLzCCASswCQYDVR0TBAIwADAdBgNVHQ4EFgQUk+GhjklDbgOwyDPtDfN7sBIe
Gacwgf4GA1UdIwSB9jCB84AUXya/mQpb4Ym2IJPdvt3f5TKwv4ChgcikgcUwgcIx
CzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTESMBAGA1UEBxMJU3Vubnl2YWxlMRUw
EwYDVQQKEwxPcHN3YXJlIEluYy4xFTATBgNVBAsTDE9wc3dhcmUgVGVhbTEiMCAG
CSqGSIb3DQEJARYTc3VwcG9ydEBvcHN3YXJlLmNvbTEVMBMGA1UEAxMMYm9vdHN0
cmFwLWNhMSkwJwYDVQQFEyA1M2Y2MzE5NDVhZDllYjhjMTg5NGM2MTQ1ZjkxYjU0
NoIQU/YxlFrZ64wYlMYUX5G1RjANBgkqhkiG9w0BAQsFAAOCAQEAnh/VwV3J1r+X
+0Egfjz9gY8HeYEFlMP/rvEAVvL4VlKevL2juBo6b/8dVECU5+ADuBbWgqQwqpv2
BRfSUUJ2jMvMVojfEMH9bwd0N9KJRcx76F99w03H/oBoYFq/bRKNsl3sKJY3NA6K
u0eGvg5GWGmIwJviR7dvFdYfLSdiygrrJpqDtdMqWgomj5iS+K39CdxJHoAjl5OO
+NQl1cgwDrY7EVqZgj+C7T5de0cuE93vjod7aroHqkITd3n2hGUkfuGGPcZQnrmr
9K8K72sgZp38gpFTSy7m+kwJkyvOnwGxBR+HaGWY7facscxIeBrHg764zFqxAyU2
W917suUozQ==
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCh5J06ydqb4na3
JMVbzVjd/wWM2hehfO9rM8qT0Ubl1VaLnzNWghMKZEks415gTzYP/5jX5gkZxd0u
PR5GcWBcEEfBnyRnyechzpPQiTiaRCjGsC89++Udz0+jrSTEHvADOoTuwHAxto+J
l9xp0G0bAqt42BP579UTaT8YJ7rVdrPxmOd9Iy5gpSXWgLr+HtSYESXRRbEox59S
gAPdjiadfyPiml9NlLNsXhOn1yz44jzDk6MssY8vdPMHvbR0r/UzMUii60o9gwqw
pBx0+wswGAaI+LjrALxyp7rkW0yhP9nkKgbaFpF/bG7O92jvyDNIeV6hV3tuic5P
7W+HVJlfAgMBAAECggEABiUOwLX7qbIJTn9DTG45Yse0trlqbzM2RSvkkwK8/alA
zTDgOnbacSkIS/9fTCmFhErvyrYM/2DuubwRI5xXC3eEubkoIRZdQv+7xY0HzHcs
0wnJ6UDf2+dL/wrp29XOx1iXxhYgzApBXXgZohyKn51U09PjwjdTr5ZtkiWj5kk5
EO57L1VIVIOBRE/6a+/8sPQ8xaRQ9VEeStt4naPebrCeoQ5pCltky3ybt1llysKS
pYfOtGhldTy8lQnbwzxPaPY7t1Ep3Py38VGyRUopMILoJkjaPR3HcUTdlUOC2oW2
TRWhTV6LzkHNoNBsjdHZFnYveaLpW/2U0PZkURyAEQKBgQDk0FFtjqAsX4g/9+iq
qXEd8tma6VLTXkZJ3gGfc/uWYBqM9HPGYlKbq33qd5pfNp1sIeRO/l8jQhXQNMHB
CjPu6z3TNjgvYDJdczPHLu4Yo84f1/T3nmT2gX68VI3VcXBTHo9GfWFnnpT9f/De
OK4LEYlj03tCKWpL2AjwEUuM7wKBgQC1IM+r959/lMLEcOnOKlavmg7eOlKeOkM2
r6R5MI82FKImrw9hUU4D5zilg3vTCvC+TVnisgrOjp5lR1XQ07UGM5xSvLpksLF5
n9y+joJtNFaYMwwJjGnnsWyf3fTeqfam9CED38j05cUv5Pd6eyoeTYzuUX/o51+/
iyrqB16akQKBgQDUdc42MUnvCeGkrBgBZ4YeLeH6Yo5Cr3YKnrbZDUPd1Gyy10Ut
Pxy/aRRpAxd3M2om/q1U4AMM5Q8GHgaOrV+diBcHKIAxFVyOwyqf16bDgE4j6U2Q
IyZScdlxG/364/NNasHUzRUFtw1W+VZ5sR2CL41oAPWhcH0/4WAjMZv6RwKBgCL6
YyBigXqxz6r/4ybdJkBjD9v6h1nnBnPZF3oP1pgrA+VUiTPR767xSA8uhQsMYdFe
Pq14lH2vLQeB7yCUwbCg5t9Tcute8+b46DgkbSuJn+9kbD6rzwffS4rT4iXdzLQR
EQ8eeEBS3vGQ1fnhLxELCNw9AOaJSARFa9Ql+C8BAoGAN2yqggoBqzHN87ykFxFX
AXN6EtzuWgUCDAZ3PIY9Ry/WmcRP9DqXwdXVmKlz50ki211OTgGnambgOt5xI+9t
9/f5xO5uKftMCIHE/rQZHQRhpH9xyZ7XIE6Ed7Cr/3YcC/u1OV1g/AsijJF+TOEc
UgQZg+f6XYwx2kYk28SRuiY=
-----END PRIVATE KEY-----
