#task to restart httpd package if there is any update
- hosts: webserver2
  remote_user: user
  become: true
  become_method: sudo
  tasks:
    - name: Update apt cache
      ansible.builtin.package:
        update_cache: true

- hosts: webserver2
  remote_user: user
  become: true
  become_method: sudo
  tasks:
    - name: ensure httpd package is present
      yum:
        name: httpd
        state: latest
      register: http_results
      when: ansible_distribution == 'RedHat'

    - name: Restart httpd
      service: 
        name: httpd
        state: restart
      when: http_results.changed 

    