- name: Patch MySQL from 5.6 to 5.7
  hosts: mysqlrhel
  gather_facts: yes
  name: System Discovery
  remote_user: root #remove when running on SA Client
  become: true #remove when running on SA Client
  become_user: root #remove when running on SA Client
  vars:
    mysql_version: "5.7.44"  # Adjust as needed
    mysql_tarball: "mysql-{{ mysql_version }}-linux-glibc2.12-x86_64.tar.gz"
    #https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.44-linux-glibc2.12-x86_64.tar.gz
    mysql_download_url: "https://dev.mysql.com/get/Downloads/MySQL-5.7/{{ mysql_tarball }}"
    mysql_install_dir: "/usr/local/mysql"
    mysql_data_dir: "/usr/local/mysql/data"  # Adjust as necessary

  tasks:
    - name: Create .my.cnf for MySQL root user with credentials
      copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user = root
          password = P@ssw0rdnh2
        owner: root
        group: root
        mode: '0600'

    - name: Ensure the .my.cnf file has correct permissions
      file:
        path: /root/.my.cnf
        owner: root
        group: root
        mode: '0600'

    - name: Stop MySQL service
      service:
        name: mysqld
        state: stopped

    - name: Backup MySQL data directory
      command: "cp -r {{ mysql_data_dir }} /usr/local/data_backup"
      when: mysql_data_dir is defined

    - name: Download MySQL 5.7 tar.gz from archives
      get_url:
        url: "http://172.19.2.98/patches/{{ mysql_tarball }}"
        dest: "/tmp/mysql-5.7.44-linux-glibc2.12-x86_64.tar.gz"
        mode: '0755'


    - name: Extract MySQL tar.gz
      unarchive:
        src: "/tmp/{{ mysql_tarball }}"
        dest: "/opt/"
        remote_src: yes

    - name: Remove old MySQL installation
      command: "rm -rf {{ mysql_install_dir }}"
      when: mysql_install_dir is defined

    - name: Move new MySQL installation
      command: "mv /opt/mysql-{{ mysql_version }}-linux-glibc2.12-x86_64 {{ mysql_install_dir }}"

    # - name: Update MySQL systemd service
    #   copy:
    #     src: "{{ mysql_install_dir }}/support-files/mysql.server"
    #     dest: "/etc/init.d/mysql"
    #     mode: '0755'

    - name: Set MySQL ownership
      command: "chown -R mysql:mysql {{ mysql_install_dir }}"

    - name: Initialize MySQL data directory
      command: "{{ mysql_install_dir }}/bin/mysqld --initialize-insecure --user=mysql --datadir={{ mysql_data_dir }}"
      args:
        creates: "{{ mysql_data_dir }}/mysql"

    
    - name: remove installed data
      command: "rm -rf {{ mysql_data_dir }}"
      register: rmv
      
    
    - name: copy old data
      command: "cp -R /usr/local/data_backup {{ mysql_data_dir }}"
      register: cpbak

    - name: Change ownership of /var/lib/mysql to mysql:mysql
      file:
        path: "{{ mysql_data_dir }}"
        owner: mysql
        group: mysql
        recurse: yes

    - name: Change permissions of /var/lib/mysql to 755
      file:
        path: "{{ mysql_data_dir }}"
        mode: '0755'
        recurse: yes

    - name: reload daemon
      command: "sudo systemctl daemon-reload"
      register: daemon

    - name: Start MySQL service
      service:
        name: mysqld
        state: started
    
    # - name: restart mysqld
    #   command: "sudo systemctl restart mysqld"
    #   register: statuschk

    - name: chkstatus
      command: "sudo systemctl status mysqld"
      register: statuschk

    - name: check status
      debug:
        var: statuschk

    - name: Run MySQL upgrade
      command: "{{ mysql_install_dir }}/bin/mysql_upgrade -u root -h 127.0.0.1 -P 3306"
      register: upgrade_result

    - name: Display upgrade result
      debug:
        var: upgrade_result.stdout_lines