- name: patch mysql 
  hosts: mysqlrhel2
  become: yes
  remote_user: root
  become: true
  become_user: root
  gather_facts: yes
  tasks:

    # - name: Check current MySQL version
    #   shell: mysql --version
    #   register: mysql_version
    #   ignore_errors: yes

    # - name: Stop MySQL service if running
    #   service:
    #     name: mysqld
    #     state: stopped

    - name: Backup MySQL data directory
      command: mysqldump -u root -p --all-databases > all_databases_backup.sql


    - name: Download MySQL 5.7 tar.gz from archives
      get_url:
        url: "https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.44-linux-glibc2.12-x86_64.tar.gz"
        dest: "/tmp/mysql-5.7.44-linux-glibc2.12-x86_64.tar.gz"
        mode: '0755'
      # when: mysql_version.stdout.find('Distrib 5.6') != -1
    
    - name: stop svc
      command: sudo systemctl stop mysqld

    - name: extract mysql
      command: tar -xvzf mysql-5.7.44-linux-glibc2.12-x86_64.tar.gz

    - name: backup mysql
      command: sudo mv /usr/local/mysql /usr/local/mysql_bak

    - name: copy mysql 
      command: sudo mv mysql-5.7.44-linux-glibc2.12-x86_64 /usr/local/mysql

    - name: update permission  
      command: sudo chown -R mysql:mysql /usr/local/mysql

    - name: update permission  
      command: sudo systemctl start mysqld
    
    - name: update permission  
      command: sudo /usr/local/mysql/bin/mysql_upgrade -u root -p
    
    - name: Cleanup  
      command: sudo rm -rf /usr/local/mysql_bak



    # - name: Extract MySQL tarball
    #   unarchive:
    #     src: /var/lib/temp/mysql-5.7.44-el7-x86_64.tar.gz
    #     dest: /usr/local
    #     remote_src: yes
    #   when: mysql_version.stdout.find('Distrib 5.6') != -1

    # - name: Update symbolic link to new MySQL version
    #   file:
    #     src: /usr/local/mysql-5.7.44-el7-x86_64
    #     dest: /usr/local/mysql
    #     state: link
    #   when: mysql_version.stdout.find('Distrib 5.6') != -1

    # - name: Update MySQL configuration file
    #   copy:
    #     src: /path/to/new/my.cnf
    #     dest: /etc/my.cnf
    #   when: mysql_version.stdout.find('Distrib 5.6') != -1

    # - name: Run MySQL upgrade script
    #   shell: "/usr/local/mysql/bin/mysql_upgrade"
    #   when: mysql_version.stdout.find('Distrib 5.6') != -1

    # - name: Start MySQL service
    #   service:
    #     name: mysqld
    #     state: started

    # - name: Verify MySQL version after upgrade
    #   shell: mysql --version
    #   register: new_mysql_version
    #   when: mysql_version.stdout.find('Distrib 5.6') != -1

    # - debug:
    #     msg: "MySQL has been successfully upgraded to version {{ new_mysql_version.stdout }}."