- hosts: webserver2
  remote_user: user
  become: true
  become_method: sudo
  tasks:
    - name: Update apt cache
      ansible.builtin.package:
        update_cache: true

- hosts: webserver2
  remote_user: user
  become: true
  become_method: sudo
  tasks:
   - name: ensure httpd package is present
     yum:
       name: httpd
       state: latest
     notify: restart_httpd

  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restart