- hosts: oracle19
  remote_user: oracle
  become: true
  become_method: sudo
  name: Oracle Patch
 
  tasks:
    - name: finding python version
      shell: python3 -V
      register: pv
      ignore_errors: true

    - name: mkdirtemp
      command: mkdir /home/oracle/pyinstall
      when: pv.stdout == ""

    - name: add pyinstaller
      copy:
        src: /home/user/ansible/installers/Python-3.10.8.tgz
        dest: /home/oracle/pyinstall/Python-3.10.8.tgz
      when: pv.stdout == ""

    - name: add installpython sh
      copy:
        src: /home/user/ansible/installers/installpython.sh
        dest: /home/oracle/pyinstall/installpython.sh
      when: pv.stdout == ""

    - name: execute python installer
      command: sh /home/oracle/pyinstall/installpython.sh
      register: output
    - name: chkoutput
      debug:
        msg:
          - "{{output}}"

    - name: checking cx_oracle version
      ansible.builtin.script:
        cmd: ~/ansible/pyscripts/checkcxoracle.py
        executable: /usr/bin/python3
      register: result
      ignore_errors: True

    - name: add cx_oracle installer
      copy:
        src: /home/user/ansible/installers/cx_Oracle-7.3.0.tar.gz
        dest: /home/oracle/pyinstall/cx_Oracle-7.3.0.tar.gz
      when: pv.stdout == "" or result.failed == true

    - name: add cx_oracle installer script
      copy:
        src: /home/user/ansible/installers/installcxoracle.sh
        dest: /home/oracle/pyinstall/installcxoracle.sh
      when: pv.stdout == "" or result.failed == true

    - name: execute cx_oracle installer
      command: sh /home/oracle/pyinstall/installcxoracle.sh
      register: output2
    - name: chkoutput2
      debug:
        msg:
          - "{{output2}}"

  
   
