- hosts: postgre
  remote_user: root
  become: true
  become_user: root
  name: Postgre patch
  vars:
    ver: 16
    minorver: 0
    oldver: 15
  tasks:
    - name: Run pg_dumpall
      shell: sudo -u postgres pg_dumpall > /var/lib/pgsql/backups/backup_{{ now(utc=true,fmt='%d%m%Y') }}.sql
      register: chk1
      args:
        chdir: '/var/lib/pgsql'
    
    - name: chk backup
      debug:
        msg:
          - "{{ chk1.stdout }}"

    - name: download patch data
      command: wget https://ftp.postgresql.org/pub/source/v{{ ver }}.{{ minorver }}/postgresql-{{ ver }}.{{ minorver }}.tar.gz


    - name: Extract patch data
      command: tar -xzf postgresql-{{ ver }}.{{ minorver }}.tar.gz

    - name: install devel kit
      command: sudo yum install gcc readline-devel zlib-devel -y

    - name: configure installer
      shell: ./configure --prefix=/var/lib/pgsql/{{ ver }} --without-icu
      register: chk2
      args:
        chdir: '/root/postgresql-{{ ver }}.{{ minorver }}'

    - name: make file 
      command: make
      args:
        chdir: '/root/postgresql-{{ ver }}.{{ minorver }}'
     

    - name: make install 
      command: make install
      register: chkins
      args:
        chdir: '/root/postgresql-{{ ver }}.{{ minorver }}'
    
    - name: chk configure
      debug:
        msg:
          - "{{ chkins.stdout }}"

    - name: Create Data directory
      file:
        path: /var/lib/pgsql/{{ ver }}/data
        state: directory
        owner: postgres
        mode: 0755

    - name: Stop old svc 
      shell: sudo -u postgres pg_ctl stop -D /var/lib/pgsql/{{ oldver }}/data
      register: chk3
      args:
        chdir: '/var/lib/pgsql' 

    - name: Init new db  
      shell: sudo -u postgres /var/lib/pgsql/{{ ver }}/bin/initdb -D /var/lib/pgsql/{{ ver }}/data
      register: chk4
      args:
        chdir: '/var/lib/pgsql' 

    - name: run pg_upgrade  
      shell: sudo -u postgres /var/lib/pgsql/{{ ver }}/bin/pg_upgrade -b /usr/pgsql-{{ oldver }}/bin -B /var/lib/pgsql/{{ ver }}/bin -d /var/lib/pgsql/{{ oldver }}/data -D /var/lib/pgsql/{{ ver }}/data
      register: chk6
      args:
        chdir: '/var/lib/pgsql' 

    - name: start new db   
      shell: sudo -u postgres /var/lib/pgsql/{{ ver }}/bin/pg_ctl  -D /var/lib/pgsql/{{ ver }}/data start
      register: chk7
      args:
        chdir: '/var/lib/pgsql' 

    - name: vacuum DB    
      shell: sudo -u postgres /var/lib/pgsql/{{ ver }}/bin/vacuumdb -U postgres --all --analyze-in-stages 
      register: chk8
      args:
        chdir: '/var/lib/pgsql'
    - name: chk vacuum
      debug:
        msg:
          - "{{ chk8.stdout }}" 

    - name: change path     
      shell: export PATH=/var/lib/pgsql/{{ ver }}/bin:$PATH
      args:
        chdir: '/var/lib/pgsql' 

    - name: set commands  1    
      shell: sudo ln -s /var/lib/pgsql/{{ ver }}/bin/pg_dumpall /usr/bin/pg_dumpall --force
      args:
        chdir: '/var/lib/pgsql' 

    - name: set commands  2    
      shell: sudo ln -s /var/lib/pgsql/{{ ver }}/bin/pg_dump /usr/bin/pg_dump --force
      args:
        chdir: '/var/lib/pgsql'
    - name: set commands  3    
      shell: sudo ln -s /var/lib/pgsql/{{ ver }}/bin/pg_ctl /usr/bin/pg_ctl --force
      args:
        chdir: '/var/lib/pgsql'
    - name: set commands  4    
      shell: sudo ln -s /var/lib/pgsql/{{ ver }}/bin/psql /usr/bin/psql --force
      args:
        chdir: '/var/lib/pgsql'
    - name: set commands  5    
      shell: sudo ln -s /var/lib/pgsql/{{ ver }}/bin/pg_upgrade /usr/bin/pg_upgrade --force
      args:
        chdir: '/var/lib/pgsql'
