- hosts: win2 #change with all for SA
  gather_facts: yes
  name: Download a package from SA.
  # remote_user: root #remove when running on SA Client
  # become: true #remove when running on SA Client
  # become_user: root #remove when running on SA Client
  vars:
    - fileurl: http://172.19.2.98/patches/postgresql-15.8-1-windows-x64.exe
    - dest: /var/lib
    - installername: "postgresql-15.8-1-windows-x64.exe"
  tasks:
    # - name: Prerequisite --- download patch file
    #   get_url:
    #     url: '{{ fileurl }}'
    #     dest: "{{ dest }}"
    # - name: Download PostgreSQL 16 installer (windows)
    #   win_get_url:
    #     url: "{{ fileurl }}"
    #     dest: C:\{{ installername }}

    - name: Prerequisite --- download patch file
      command: "{{ ansible_python_interpreter }}"
      args:
        stdin: >
          from coglib import downloader;

          downloader.Tsunami().fetch_unit(downloader.DownloadUnit({{ mysql_patchid }},None,None,'{{ mysql_tarball }}', None, '/tmp'))
      register: test
      when: "'RedHat' in ansible_distribution"   
      tags: download,remote
     