- name: Get SQL Server version from Windows Registry
  hosts: winsqlservercls1  # Replace with your actual Windows host group winsqlservercls1
  gather_facts: yes
  vars:
    isCluster: "NA"
    instancelist: []
    prodlevellist: []
    pathloglist: []
    getsqlnumberlist: []
    ipaddr: ""
  tasks:
    - debug:
        var: ansible_facts.interfaces
    - set_fact:
        ethernet0_ip: "{{ ansible_facts.interfaces | selectattr('connection_name', 'equalto', 'Ethernet0') | map(attribute='ipv4.address') | first }}"
    - debug:
        var: ethernet0_ip