- name: Automate SQL Server Cluster Patching
  hosts: oracleRAC1
  gather_facts: true
  remote_user: root #remove when running on SA Client
  become: true #remove when running on SA Client
  become_user: root #remove when running on SA Client
  vars:
    - dest: C:\Temp
    - dest2: C:\
  tasks:
    
    - name: "get user grid"
      shell: sudo -u oracle bash -c 'source ~/.bash_profile && echo $ORACLE_HOME'
      register: usergrid
     
    - name: Debug nodes detected
      debug:
        var: usergrid.stdout
