- name: Check if a file exists in root directory
  hosts: localhost
  tasks:
    - name: Check file existence
      ansible.builtin.stat:
        path: "/credentials.b64"
      register: file_stat

    - name: Print file existence status
      debug:
        msg: "File exists!" 
      when: file_stat.stat.exists