- name: Check MySQL Installation in Windows Registry
  hosts: winsqlserver3
  tasks:
    - name: Search for MySQL Server in installed programs
      win_shell: |
        Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* |
        Select-Object DisplayName | Where-Object { $_.DisplayName -match "MySQL Server" }
      register: mysql_registry
      ignore_errors: yes
      
    - name: testdebug
      debug:
        var: mysql_registry

    - name: Show MySQL installation status
      debug:
        msg: "{{ 'MySQL Server is installed' if mysql_registry.stdout else 'MySQL Server is not installed' }}"
    
    - name: Search for PostgreSQL in installed programs
      win_shell: |
        Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* |
        Select-Object DisplayName | Where-Object { $_.DisplayName -match "PostgreSQL" }
      register: postgres_registry
      ignore_errors: yes

    - name: Show PostgreSQL installation status
      debug:
        msg: "{{ 'PostgreSQL is installed' if postgres_registry.stdout else 'PostgreSQL is not installed' }}"

    - name: Search for SQL Server in installed programs
      win_shell: |
        Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* |
        Select-Object DisplayName | Where-Object { $_.DisplayName -match "SQL Server" }
      register: sql_registry
      ignore_errors: yes

    - name: Show SQL Server installation status
      debug:
        msg: "{{ 'Microsoft SQL Server is installed' if sql_registry.stdout else 'Microsoft SQL Server is not installed' }}"
